###* Base Environments
@BASE_URL = http://localhost:3333
@RESOURCE = products

###! Products
GET {{BASE_URL}}/{{RESOURCE}}?name

###
POST {{BASE_URL}}/{{RESOURCE}}
Content-Type: application/json

{
  "name": "Executivo de frango grelhado",
  "price": 70
}
###
PUT  {{BASE_URL}}/{{RESOURCE}}/7
Content-Type: application/json

{
  "name": "Executivo de frango grelhado",
  "price": 70
}

###
DELETE {{BASE_URL}}/{{RESOURCE}}/9
