###* Base Environments
@BASE_URL = http://localhost:3333
@RESOURCE = products
@RESOURCE_TABLES = tables
@RESOURCE_TABLES_SESSIONS = tables-sessions
@RESOURCE_TABLES_ORDERS = orders

###! Products
GET {{BASE_URL}}/{{RESOURCE}}

###
POST {{BASE_URL}}/{{RESOURCE}}
Content-Type: application/json

{
  "name": "Executivo de frango grelhado",
  "price": 70
}
###
PUT  {{BASE_URL}}/{{RESOURCE}}/7
Content-Type: application/json

{
  "name": "Executivo",
  "price": 70
}

###
DELETE {{BASE_URL}}/{{RESOURCE}}/9

### TABLES
GET {{BASE_URL}}/{{RESOURCE_TABLES}}

### TABLES-SESSIONS
POST  {{BASE_URL}}/{{RESOURCE_TABLES_SESSIONS}}
Content-Type: application/json

{
  "table_id": 1
}

### 
GET {{BASE_URL}}/{{RESOURCE_TABLES_SESSIONS}}

### 
PATCH {{BASE_URL}}/{{RESOURCE_TABLES_SESSIONS}}/1

### 
POST {{BASE_URL}}/{{RESOURCE_TABLES_ORDERS}}
Content-Type: application/json

{
  "table_session_id": 3,
  "product_id": 28,
  "quantity": 2
}

### 
GET  {{BASE_URL}}/{{RESOURCE_TABLES_ORDERS}}/table-session/
### 
GET  {{BASE_URL}}/{{RESOURCE_TABLES_ORDERS}}/table-session/3/total

